### ISSUE TITLE
Missing orcid_icon.png files in dspace_5x.patch and dspace_6x.patch

### ISSUE THREAD

**Issue by uofmsean** [atmire/ORCID-rest-api#2]
The patch files [dspace_5x.patch](https://github.com/atmire/expanded-ORCID-support/blob/master/patches/dspace_5x.patch) and [dspace_6x.patch](https://github.com/atmire/expanded-ORCID-support/blob/master/patches/dspace_6x.patch) are missing the orcid_icon.png binary diffs. The patches need to be created using the --binary option for git diff. Also, the [Download patch](https://atmire.github.io/expanded-ORCID-support/#/prerequisites?id=download-patch) instructions should mention the --binary option for those who want to create their own patch file.

**Comment by jonas-atmire** [comment]
@uofmsean 
You seem to be correct, the patch files no longer contain the binary diffs, which is strange.
I've recreated them using the --binary option (As I did before as well), and also updated the documentation accordingly.
The diffs are now present in the patch file https://github.com/atmire/expanded-ORCID-support/pull/4/files
Application of the patch also adds in the icon images to the codebase.
